#!/usr/bin/env bash
set -euo pipefail

project_path="${1:-$(pwd)}"
codex_home="${HOME}/.codex"
preset_dir="${codex_home}/presets"
mcp_preset_dir="${preset_dir}/mcp"
skill_preset_dir="${preset_dir}/skills"
base_preset="${preset_dir}/base-project.toml"

project_path="$(realpath "$project_path")"
project_codex_dir="${project_path}/.codex"
project_config="${project_codex_dir}/config.toml"
project_skills_dir="${project_codex_dir}/skills"
codex_home_resolved="$(realpath "$codex_home")"

case "$project_path" in
  "$codex_home_resolved"|"$codex_home_resolved"/*)
    printf 'ProjectPath esta dentro do runtime global do Codex. Abortando para evitar .codex dentro de ~/.codex: %s\n' "$project_path" >&2
    exit 1
    ;;
esac

if [[ ! -d "$mcp_preset_dir" ]]; then
  printf 'Diretorio de presets MCP nao encontrado: %s\n' "$mcp_preset_dir" >&2
  exit 1
fi

select_numbered_items() {
  local title="$1"
  local empty_label="$2"
  shift 2
  local items=("$@")

  printf '\n%s\n\n' "$title" >&2
  if [[ ${#items[@]} -eq 0 ]]; then
    printf '%s\n' "$empty_label" >&2
    return 0
  fi

  local i label
  for i in "${!items[@]}"; do
    label="$(basename "${items[$i]}")"
    label="${label%.*}"
    label="${label%.template}"
    printf '[%d] %s\n' "$((i + 1))" "$label" >&2
  done

  printf '\nDigite os numeros separados por virgula. Ex: 1,3,4\nENTER = nenhum\n\n' >&2
  read -r -p "Selecionar: " input_raw

  [[ -z "${input_raw//[[:space:]]/}" ]] && return 0
  IFS=',' read -ra indexes <<< "$input_raw"
  local idx n
  for idx in "${indexes[@]}"; do
    idx="${idx//[[:space:]]/}"
    [[ -z "$idx" ]] && continue
    if [[ ! "$idx" =~ ^[0-9]+$ ]]; then
      printf 'Indice invalido: %s\n' "$idx" >&2
      exit 1
    fi
    n="$idx"
    if (( n < 1 || n > ${#items[@]} )); then
      printf 'Indice fora do intervalo: %s\n' "$n" >&2
      exit 1
    fi
    printf '%s\n' "${items[$((n - 1))]}"
  done
}

mapfile -t mcp_presets < <(find "$mcp_preset_dir" -maxdepth 1 -type f -name '*.toml' | sort)
mapfile -t selected_mcps < <(select_numbered_items "MCP presets disponiveis:" "Nenhum preset MCP encontrado." "${mcp_presets[@]}")

selected_mcp_names=()
for preset in "${selected_mcps[@]}"; do
  name="$(basename "$preset")"
  name="${name%.toml}"
  name="${name%.template}"
  selected_mcp_names+=("$name")
done

skill_presets=()
if [[ -d "$skill_preset_dir" ]]; then
  mapfile -t skill_presets < <(find "$skill_preset_dir" -maxdepth 1 -type f -name '*.json' | sort)
fi

mapfile -t selected_skill_paths < <(python3 - "$skill_preset_dir" "${skill_presets[@]}" <<'PY'
import json
import pathlib
import sys

paths = [pathlib.Path(p) for p in sys.argv[2:]]
print("\nSkill presets disponiveis:\n", file=sys.stderr)
if not paths:
    print("Nenhum preset de skill encontrado.", file=sys.stderr)
    sys.exit(0)
items = []
for path in paths:
    data = json.loads(path.read_text(encoding="utf-8"))
    items.append((path, data.get("name", ""), data.get("description", "")))
for index, (_, name, description) in enumerate(items, 1):
    print(f"[{index}] {name} - {description}", file=sys.stderr)
print("\nDigite os numeros separados por virgula. Ex: 1,3,4\nENTER = nenhum\n", file=sys.stderr)
raw = input("Selecionar: ").strip()
if not raw:
    sys.exit(0)
seen = set()
for part in raw.split(","):
    part = part.strip()
    if not part:
        continue
    if not part.isdigit():
        raise SystemExit(f"Indice invalido: {part}")
    idx = int(part)
    if idx < 1 or idx > len(items):
        raise SystemExit(f"Indice fora do intervalo: {idx}")
    path = str(items[idx - 1][0])
    if path not in seen:
        print(path)
        seen.add(path)
PY
)

selected_skill_names=()
mkdir -p "$project_codex_dir"

{
  printf '# Generated by bootstrap-codex-project.sh\n'
  printf '# Project: %s\n\n' "$project_path"
  if [[ -f "$base_preset" ]]; then
    sed '${/^$/d;}' "$base_preset"
    printf '\n'
  fi
  for preset in "${selected_mcps[@]}"; do
    printf '\n# --- MCP preset: %s ---\n' "$(basename "$preset" .toml)"
    sed '${/^$/d;}' "$preset"
    printf '\n'
  done
} > "$project_config"

printf '\nConfig local criada:\n%s\n' "$project_config"

if [[ ${#selected_mcp_names[@]} -gt 0 ]]; then
  printf '\nMCPs habilitados:\n'
  printf -- '- %s\n' "${selected_mcp_names[@]}"
fi

for preset in "${selected_skill_paths[@]}"; do
  mapfile -t skill_info < <(python3 - "$preset" "$codex_home" <<'PY'
import json
import pathlib
import sys

data = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
name = data.get("name")
if not name:
    raise SystemExit("Preset de skill sem campo 'name'.")
source = data.get("source") or f"{sys.argv[2]}/skills/{name}"
source = source.replace("{{CODEX_HOME}}", sys.argv[2])
print(name)
print(source)
PY
)
  name="${skill_info[0]}"
  source="${skill_info[1]}"
  target="${project_skills_dir}/${name}"
  if [[ ! -e "$source" ]]; then
    printf 'Skill source nao encontrado: %s\n' "$source" >&2
    exit 1
  fi
  mkdir -p "$project_skills_dir"
  rm -rf "$target"
  if ! ln -s "$source" "$target" 2>/dev/null; then
    cp -a "$source" "$target"
  fi
  selected_skill_names+=("$name")
done

if [[ ${#selected_skill_names[@]} -gt 0 ]]; then
  printf '\nSkills habilitadas:\n'
  printf -- '- %s\n' "${selected_skill_names[@]}"
fi

resolve_script="${codex_home}/scripts/resolve-codex-services.sh"
start_services_script="${codex_home}/scripts/start-codex-services.sh"
if [[ -x "$resolve_script" && -x "$start_services_script" ]]; then
  resolved="$("$resolve_script" --mcps "${selected_mcp_names[@]}" --skills "${selected_skill_names[@]}")"
  mapfile -t services_to_start < <(python3 -c 'import json,sys; print("\n".join(json.loads(sys.argv[1]).get("services", [])))' "$resolved")
  mapfile -t profiles_to_use < <(python3 -c 'import json,sys; print("\n".join(json.loads(sys.argv[1]).get("profiles", [])))' "$resolved")
  if [[ ${#services_to_start[@]} -gt 0 ]]; then
    printf '\nServicos Docker necessarios:\n'
    printf -- '- %s\n' "${services_to_start[@]}"
    if [[ ${#profiles_to_use[@]} -gt 0 ]]; then
      printf '\nProfiles Docker necessarios:\n'
      printf -- '- %s\n' "${profiles_to_use[@]}"
    fi
    read -r -p "Deseja iniciar agora? [S/n] " answer
    if [[ -z "$answer" || "${answer,,}" == s* ]]; then
      "$start_services_script" --services "${services_to_start[@]}" --profiles "${profiles_to_use[@]}"
    fi
  fi
fi
